#!/usr/bin/env python3

from __future__ import annotations

import copy
import datetime as dt
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit, urlunsplit

import requests
import yaml
from bs4 import BeautifulSoup, FeatureNotFound
from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "_data"
ASSET_DIR = ROOT / "assets" / "cosmic"
CONFIG_PATH = ROOT / "_config.yml"
DEFAULT_SEED_PATH = ROOT / "scripts" / "linkedin_seed.yml"
SCHEMA_VERSION = 2
DEFAULT_TIMEOUT_SECONDS = 20
PUBLIC_SYNC_SOURCE = "linkedin-public"
CURATED_SEED_SOURCE = "linkedin-curated-seed"
MACHINE_HEADER = "# MACHINE-MANAGED FILE. DO NOT EDIT.\n# Generated by scripts/sync_linkedin_content.py.\n"
PUBLIC_FETCH_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
}
BLOCK_MARKERS = (
    'id="error404"',
    'class="error-pages"',
    "page does not exist",
    "this page doesn't exist",
    "linkedin.com/404",
    "authwall",
    "captcha",
    "security verification",
    "sign in to linkedin",
    "join linkedin",
)
TRACKING_QUERY_KEYS = {
    "lipi",
    "midtoken",
    "midtoken2",
    "trackingid",
    "trk",
    "trkemail",
    "trkinfo",
    "originalsubdomain",
    "refid",
    "refid2",
    "sessionredirect",
    "srchid",
    "upsellorderorigin",
}
NOISE_PATTERNS = (
    r"\b\d+[\d,]*\s+(?:reactions?|comments?|impressions?|followers?|connections?)\b",
    r"\bprivate to you\b",
    r"\bwho viewed your profile\b",
    r"\bshow all activity\b",
    r"\bsee all activity\b",
    r"\bedit public profile\b",
    r"\bmessage\b",
    r"\bfollow\b",
    r"\bconnect\b",
    r"\bmore\b",
)
PROFILE_REQUIRED_FIELDS = ("full_name", "headline", "about_short", "profile_url")


SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "linkedin_profile",
        "linkedin_experience",
        "linkedin_featured",
        "linkedin_updates",
    ],
    "properties": {
        "linkedin_profile": {
            "type": "object",
            "required": [
                "full_name",
                "headline",
                "headline_short",
                "location",
                "organization",
                "current_role",
                "profile_url",
                "profile_image_url",
                "about_full",
                "about_short",
                "top_skills",
                "last_synced_at",
                "source",
            ],
            "properties": {
                "full_name": {"type": "string", "maxLength": 120},
                "headline": {"type": "string", "maxLength": 220},
                "headline_short": {"type": "string", "maxLength": 110},
                "location": {"type": "string", "maxLength": 120},
                "organization": {"type": "string", "maxLength": 120},
                "current_role": {"type": "string", "maxLength": 120},
                "profile_url": {"type": "string", "maxLength": 320},
                "profile_image_url": {"type": "string", "maxLength": 320},
                "about_full": {"type": "string", "maxLength": 1400},
                "about_short": {"type": "string", "maxLength": 320},
                "top_skills": {
                    "type": "array",
                    "maxItems": 8,
                    "items": {"type": "string", "maxLength": 40},
                },
                "last_synced_at": {"type": "string", "maxLength": 40},
                "source": {"type": "string", "const": "linkedin"},
            },
            "additionalProperties": False,
        },
        "linkedin_experience": {
            "type": "array",
            "maxItems": 8,
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "role",
                    "organization",
                    "date_range",
                    "location",
                    "description_full",
                    "description_short",
                    "bullets",
                    "source",
                ],
                "properties": {
                    "id": {"type": "string", "maxLength": 80},
                    "role": {"type": "string", "maxLength": 90},
                    "organization": {"type": "string", "maxLength": 90},
                    "date_range": {"type": "string", "maxLength": 80},
                    "location": {"type": "string", "maxLength": 100},
                    "description_full": {"type": "string", "maxLength": 900},
                    "description_short": {"type": "string", "maxLength": 240},
                    "bullets": {
                        "type": "array",
                        "maxItems": 4,
                        "items": {"type": "string", "maxLength": 180},
                    },
                    "canonical_url": {"type": ["string", "null"], "maxLength": 320},
                    "source": {"type": "string", "const": "linkedin"},
                },
                "additionalProperties": False,
            },
        },
        "linkedin_featured": {
            "type": "array",
            "maxItems": 6,
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "type",
                    "title",
                    "subtitle",
                    "summary_short",
                    "url",
                    "source",
                ],
                "properties": {
                    "id": {"type": "string", "maxLength": 80},
                    "type": {
                        "type": "string",
                        "enum": ["honor", "post", "link", "project"],
                    },
                    "title": {"type": "string", "maxLength": 80},
                    "subtitle": {"type": "string", "maxLength": 80},
                    "summary_full": {"type": "string", "maxLength": 900},
                    "summary_short": {"type": "string", "maxLength": 220},
                    "url": {"type": ["string", "null"], "maxLength": 320},
                    "source": {"type": "string", "const": "linkedin"},
                },
                "additionalProperties": False,
            },
        },
        "linkedin_updates": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "kind",
                    "title",
                    "summary_short",
                    "posted_relative",
                    "canonical_url",
                    "source",
                ],
                "properties": {
                    "id": {"type": "string", "maxLength": 80},
                    "kind": {
                        "type": "string",
                        "enum": ["post", "milestone", "announcement"],
                    },
                    "title": {"type": "string", "maxLength": 80},
                    "summary_full": {"type": "string", "maxLength": 900},
                    "summary_short": {"type": "string", "maxLength": 220},
                    "posted_relative": {"type": "string", "maxLength": 60},
                    "canonical_url": {"type": ["string", "null"], "maxLength": 320},
                    "source": {"type": "string", "const": "linkedin"},
                },
                "additionalProperties": False,
            },
        },
    },
    "additionalProperties": False,
}


class LinkedInSyncError(RuntimeError):
    pass


class LinkedInUnavailableError(LinkedInSyncError):
    pass


@dataclass
class FetchResult:
    url: str
    final_url: str
    status_code: int
    fetched_at: str
    html: str


def soup_parser(html: str) -> BeautifulSoup:
    try:
        return BeautifulSoup(html, "lxml")
    except FeatureNotFound:
        return BeautifulSoup(html, "html.parser")


def normalize_whitespace(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", " ", value).strip()


def strip_html(value: str | None) -> str:
    if not value:
        return ""
    raw = str(value)
    if "<" in raw and ">" in raw:
        return soup_parser(raw).get_text(" ", strip=True)
    return raw


def clean_text(value: str | None) -> str:
    text = normalize_whitespace(strip_html(value))
    if not text:
        return ""
    text = text.replace("\u2013", "-").replace("\u2014", "-")
    text = text.replace("\u00b7", " - ")
    text = re.sub(r"\s*[\u2022•]+\s*", "; ", text)
    text = re.sub(r"\s*\|\s*", " - ", text)
    text = re.sub(r"\s+/\s+", "/", text)
    for pattern in NOISE_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE)
    text = re.sub(r"\b(Edited|View|See more|See less|Show more|Show less)\b", "", text, flags=re.IGNORECASE)
    text = re.sub(r"([!?.,;:])\1+", r"\1", text)
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+-\s+-\s+", " - ", text)
    return normalize_whitespace(text).strip(" -;,")


def smart_truncate(value: str | None, limit: int) -> str:
    text = clean_text(value)
    if len(text) <= limit:
        return text

    sentences = [segment.strip() for segment in re.split(r"(?<=[.!?])\s+", text) if segment.strip()]
    candidate = ""
    for sentence in sentences:
        joined = sentence if not candidate else f"{candidate} {sentence}"
        if len(joined) <= limit:
            candidate = joined
        else:
            break
    if candidate and len(candidate) >= max(40, int(limit * 0.45)):
        return candidate.rstrip(" ,;:-")

    preview = text[: limit + 1]
    for delimiter in (". ", "; ", ": ", ", ", " - ", " "):
        idx = preview.rfind(delimiter)
        if idx >= max(0, limit - 42):
            return preview[:idx].rstrip(" ,;:-") + "..."
    return preview[:limit].rstrip(" ,;:-") + "..."


def slugify(value: str | None) -> str:
    text = clean_text(value).lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "item"


def stable_id(prefix: str, *values: str) -> str:
    base = "-".join(filter(None, (slugify(value) for value in values))) or prefix
    digest = hashlib.sha1("|".join(values).encode("utf-8")).hexdigest()[:8]
    trimmed = base[: max(12, 62 - len(prefix))].strip("-")
    return f"{prefix}-{trimmed}-{digest}"[:80]


def strip_tracking_url(value: str | None) -> str | None:
    raw = normalize_whitespace(value)
    if not raw:
        return None
    parts = urlsplit(raw)
    filtered_pairs = []
    for key, item_value in parse_qsl(parts.query, keep_blank_values=True):
        lowered = key.casefold()
        if lowered.startswith("utm_") or lowered in TRACKING_QUERY_KEYS:
            continue
        filtered_pairs.append((key, item_value))
    query = urlencode(filtered_pairs, doseq=True)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, query, ""))


def unique_preserve(values: list[str], limit: int, *, max_length: int = 40) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    for raw_value in values:
        value = smart_truncate(raw_value, max_length)
        if not value:
            continue
        folded = value.casefold()
        if folded in seen:
            continue
        ordered.append(value)
        seen.add(folded)
        if len(ordered) >= limit:
            break
    return ordered


def sentence_bullets(value: str, *, max_items: int = 4) -> list[str]:
    text = clean_text(value)
    if not text:
        return []
    parts = [segment.strip() for segment in re.split(r"(?<=[.!?;])\s+", text) if segment.strip()]
    if len(parts) <= 1:
        parts = [segment.strip() for segment in re.split(r"\s+-\s+|;", text) if segment.strip()]
    return unique_preserve(parts, max_items, max_length=180)


def split_role_and_org(value: str) -> tuple[str, str]:
    text = clean_text(value)
    if not text:
        return "", ""
    for delimiter in (" at ", " @ "):
        if delimiter in text.lower():
            match = re.split(delimiter, text, flags=re.IGNORECASE, maxsplit=1)
            if len(match) == 2:
                return smart_truncate(match[0], 90), smart_truncate(match[1], 90)
    return smart_truncate(text, 90), ""


def remove_duplicate_punctuation(value: str) -> str:
    text = clean_text(value)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"([!?.,;:])\1+", r"\1", text)
    return text.strip()


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def resolve_profile_url(explicit_url: str | None = None) -> str:
    if explicit_url:
        return explicit_url

    config = load_yaml(CONFIG_PATH)
    author = config.get("author") or {}
    linkedin_value = normalize_whitespace(str(author.get("linkedin") or ""))
    if linkedin_value:
        if linkedin_value.startswith("http://") or linkedin_value.startswith("https://"):
            return linkedin_value
        return f"https://www.linkedin.com/in/{linkedin_value.strip('/')}/"

    raise LinkedInSyncError("LinkedIn profile URL could not be resolved from CLI input or _config.yml.")


def detect_unavailable(status_code: int, final_url: str, html: str) -> str | None:
    if status_code >= 400:
        return f"LinkedIn returned HTTP {status_code}."

    lowered = html.lower()
    for marker in BLOCK_MARKERS:
        if marker in lowered:
            return f"LinkedIn public profile response looked blocked or unavailable ({marker})."

    if "/404" in final_url.rstrip("/"):
        return "LinkedIn redirected to a 404 page."

    if len(lowered.strip()) < 1200:
        return "LinkedIn public response was too short to trust."

    if "linkedin" not in lowered:
        return "LinkedIn response did not resemble a profile page."

    return None


def fetch_public_profile_html(profile_url: str, *, timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS, verbose: bool = False) -> FetchResult:
    session = requests.Session()
    response = session.get(profile_url, headers=PUBLIC_FETCH_HEADERS, timeout=timeout_seconds, allow_redirects=True)
    html = response.text

    if verbose:
        print(f"Fetched {profile_url} -> {response.url} [{response.status_code}]")

    blocked_reason = detect_unavailable(response.status_code, response.url, html)
    if blocked_reason:
        raise LinkedInUnavailableError(blocked_reason)

    return FetchResult(
        url=profile_url,
        final_url=response.url,
        status_code=response.status_code,
        fetched_at=dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat(),
        html=html,
    )


def flatten_json_ld(node: Any) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    if isinstance(node, dict):
        if isinstance(node.get("@graph"), list):
            for child in node["@graph"]:
                items.extend(flatten_json_ld(child))
        else:
            items.append(node)
    elif isinstance(node, list):
        for child in node:
            items.extend(flatten_json_ld(child))
    return items


def extract_json_ld_records(soup: BeautifulSoup) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for script in soup.find_all("script", attrs={"type": re.compile("ld\\+json", re.I)}):
        raw_text = script.string or script.get_text("", strip=True)
        if not raw_text:
            continue
        try:
            parsed = json.loads(raw_text)
        except json.JSONDecodeError:
            continue
        records.extend(flatten_json_ld(parsed))
    return records


def first_meta(soup: BeautifulSoup, *selectors: tuple[str, str]) -> str:
    for attr_name, attr_value in selectors:
        tag = soup.find("meta", attrs={attr_name: attr_value})
        if tag and tag.get("content"):
            return clean_text(str(tag["content"]))
    return ""


def find_person_record(records: list[dict[str, Any]]) -> dict[str, Any]:
    for record in records:
        raw_type = record.get("@type") or record.get("type")
        types = raw_type if isinstance(raw_type, list) else [raw_type]
        type_names = {str(value).casefold() for value in types}
        if "person" in type_names:
            return record
    return {}


def meta_description_segments(description: str) -> list[str]:
    return [clean_text(segment) for segment in description.split(" - ") if clean_text(segment)]


def parse_location(soup: BeautifulSoup, person: dict[str, Any], description: str) -> str:
    home_location = person.get("homeLocation")
    if isinstance(home_location, dict):
        location = clean_text(str(home_location.get("name") or ""))
    else:
        location = clean_text(str(home_location or ""))
    if location:
        return smart_truncate(location, 120)

    segments = meta_description_segments(description)
    if len(segments) >= 2 and "," in segments[1]:
        return smart_truncate(segments[1], 120)

    selectors = [
        "[data-test-id='top-card-location']",
        ".top-card-layout__first-subline",
        ".top-card__subline-item",
        "[data-section='location']",
    ]
    for selector in selectors:
        candidate = soup.select_one(selector)
        if candidate:
            text = clean_text(candidate.get_text(" ", strip=True))
            if text and "linkedin" not in text.casefold():
                return smart_truncate(text, 120)

    return ""


def parse_top_skills(soup: BeautifulSoup) -> list[str]:
    headings = soup.find_all(re.compile("^h[1-6]$"))
    for heading in headings:
        heading_text = clean_text(heading.get_text(" ", strip=True)).casefold()
        if "skills" not in heading_text:
            continue
        container = heading.find_parent(["section", "article", "div"]) or heading.parent
        if not container:
            continue
        values: list[str] = []
        for candidate in container.find_all(["li", "span", "a"], limit=30):
            text = clean_text(candidate.get_text(" ", strip=True))
            if 2 <= len(text) <= 60:
                values.append(text)
        skills = unique_preserve(values, 8, max_length=40)
        if skills:
            return skills
    return []


def parse_section_cards(soup: BeautifulSoup, section_names: tuple[str, ...]) -> list[BeautifulSoup]:
    cards: list[BeautifulSoup] = []
    heading_tags = soup.find_all(re.compile("^h[1-6]$"))
    for heading in heading_tags:
        heading_text = clean_text(heading.get_text(" ", strip=True)).casefold()
        if not any(section_name in heading_text for section_name in section_names):
            continue
        container = heading.find_parent(["section", "article", "div"]) or heading.parent
        if not container:
            continue
        seen: set[int] = set()
        for child in container.find_all(["article", "li", "div"], recursive=True):
            child_text = clean_text(child.get_text(" ", strip=True))
            if len(child_text) < 25:
                continue
            if id(child) in seen:
                continue
            seen.add(id(child))
            cards.append(child)
            if len(cards) >= 12:
                break
        if cards:
            break
    return cards


def extract_anchor_url(node: BeautifulSoup, base_url: str) -> str | None:
    anchor = node.find("a", href=True)
    if not anchor:
        return None
    return strip_tracking_url(urljoin(base_url, str(anchor["href"]).strip()))


def detect_item_type(title: str, subtitle: str, fallback: str) -> str:
    combined = f"{title} {subtitle}".casefold()
    if any(keyword in combined for keyword in ("award", "honor", "fellowship", "recognition")):
        return "honor"
    if any(keyword in combined for keyword in ("project", "portfolio", "case study", "demo")):
        return "project"
    if any(keyword in combined for keyword in ("post", "article", "announcement", "update")):
        return "post"
    return fallback


def detect_update_kind(title: str, summary: str) -> str:
    combined = f"{title} {summary}".casefold()
    if any(keyword in combined for keyword in ("announced", "launch", "released", "published")):
        return "announcement"
    if any(keyword in combined for keyword in ("award", "joined", "graduated", "promoted", "accepted")):
        return "milestone"
    return "post"


def normalize_relative_label(value: str) -> str:
    text = clean_text(value)
    return smart_truncate(text, 60)


def normalize_seed_list(value: Any, label: str) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        return [value]
    raise LinkedInSyncError(f"{label} in the LinkedIn seed file must be a list or string.")


def normalize_seed_mapping(value: Any, label: str) -> dict[str, Any]:
    if value is None:
        return {}
    if isinstance(value, dict):
        return value
    raise LinkedInSyncError(f"{label} in the LinkedIn seed file must be an object.")


def normalize_curated_seed(raw_data: dict[str, Any], profile_url: str, checked_at: str) -> dict[str, Any]:
    profile_key = "profile" if "profile" in raw_data else "linkedin_profile"
    experience_key = "experience" if "experience" in raw_data else "linkedin_experience"
    featured_key = "featured" if "featured" in raw_data else "linkedin_featured"
    updates_key = "updates" if "updates" in raw_data else "linkedin_updates"

    profile_raw = normalize_seed_mapping(raw_data.get(profile_key), profile_key)
    experience_raw = normalize_seed_list(raw_data.get(experience_key), experience_key)
    featured_raw = normalize_seed_list(raw_data.get(featured_key), featured_key)
    updates_raw = normalize_seed_list(raw_data.get(updates_key), updates_key)

    full_name = clean_text(str(profile_raw.get("full_name") or profile_raw.get("name") or ""))
    headline = clean_text(str(profile_raw.get("headline") or profile_raw.get("headline_short") or ""))
    current_role = clean_text(str(profile_raw.get("current_role") or ""))
    organization = clean_text(str(profile_raw.get("organization") or ""))
    derived_role, derived_org = split_role_and_org(headline)
    current_role = current_role or derived_role
    organization = organization or derived_org

    about_full = clean_text(
        str(
            profile_raw.get("about_full")
            or profile_raw.get("about")
            or profile_raw.get("summary")
            or ""
        )
    )
    about_short = clean_text(str(profile_raw.get("about_short") or about_full))
    profile_image_url = strip_tracking_url(str(profile_raw.get("profile_image_url") or "")) or ""
    profile_top_skills = unique_preserve(
        [str(item) for item in normalize_seed_list(profile_raw.get("top_skills") or profile_raw.get("skills"), "profile.top_skills")],
        8,
        max_length=40,
    )

    experience: list[dict[str, Any]] = []
    for raw_item in experience_raw:
        item = normalize_seed_mapping(raw_item, "experience item")
        role = clean_text(str(item.get("role") or ""))
        employer = clean_text(str(item.get("organization") or item.get("company") or ""))
        if not role or not employer:
            continue

        date_range = clean_text(str(item.get("date_range") or item.get("dates") or ""))
        location = clean_text(str(item.get("location") or ""))
        bullets_source = [str(value) for value in normalize_seed_list(item.get("bullets"), "experience.bullets")]
        bullets = unique_preserve(bullets_source, 4, max_length=180)
        description_full = clean_text(
            str(item.get("description_full") or item.get("description") or " ".join(bullets))
        )
        description_short = clean_text(str(item.get("description_short") or description_full))

        experience.append(
            {
                "id": stable_id("experience", role, employer, date_range or location),
                "role": smart_truncate(role, 90),
                "organization": smart_truncate(employer, 90),
                "date_range": smart_truncate(date_range, 80),
                "location": smart_truncate(location, 100),
                "description_full": smart_truncate(description_full, 900),
                "description_short": smart_truncate(description_short, 240),
                "bullets": bullets or sentence_bullets(description_full),
                "canonical_url": strip_tracking_url(str(item.get("canonical_url") or item.get("url") or "")),
                "source": "linkedin",
            }
        )
        if len(experience) >= 8:
            break

    featured: list[dict[str, Any]] = []
    for raw_item in featured_raw:
        item = normalize_seed_mapping(raw_item, "featured item")
        title = clean_text(str(item.get("title") or ""))
        if not title:
            continue

        subtitle = clean_text(str(item.get("subtitle") or item.get("label") or ""))
        summary_full = clean_text(str(item.get("summary_full") or item.get("summary") or item.get("description") or ""))
        item_type = clean_text(str(item.get("type") or ""))
        featured.append(
            {
                "id": stable_id("featured", title, subtitle or item_type),
                "type": detect_item_type(title, subtitle, item_type or "project"),
                "title": smart_truncate(title, 80),
                "subtitle": smart_truncate(subtitle, 80),
                "summary_full": smart_truncate(summary_full, 900),
                "summary_short": smart_truncate(summary_full or subtitle, 220),
                "url": strip_tracking_url(str(item.get("url") or item.get("canonical_url") or "")),
                "source": "linkedin",
            }
        )
        if len(featured) >= 6:
            break

    updates: list[dict[str, Any]] = []
    for raw_item in updates_raw:
        item = normalize_seed_mapping(raw_item, "updates item")
        title = clean_text(str(item.get("title") or ""))
        if not title:
            continue

        summary_full = clean_text(str(item.get("summary_full") or item.get("summary") or item.get("description") or ""))
        posted_relative = normalize_relative_label(
            str(item.get("posted_relative") or item.get("label") or item.get("date_label") or "")
        )
        raw_kind = clean_text(str(item.get("kind") or ""))
        updates.append(
            {
                "id": stable_id("update", title, posted_relative or raw_kind),
                "kind": raw_kind or detect_update_kind(title, summary_full),
                "title": smart_truncate(title, 80),
                "summary_full": smart_truncate(summary_full, 900),
                "summary_short": smart_truncate(summary_full or title, 220),
                "posted_relative": posted_relative,
                "canonical_url": strip_tracking_url(str(item.get("canonical_url") or item.get("url") or "")),
                "source": "linkedin",
            }
        )
        if len(updates) >= 3:
            break

    payload = {
        "linkedin_profile": {
            "full_name": smart_truncate(full_name, 120),
            "headline": smart_truncate(headline, 220),
            "headline_short": smart_truncate(str(profile_raw.get("headline_short") or headline), 110),
            "location": smart_truncate(str(profile_raw.get("location") or ""), 120),
            "organization": smart_truncate(organization, 120),
            "current_role": smart_truncate(current_role, 120),
            "profile_url": strip_tracking_url(str(profile_raw.get("profile_url") or profile_url)) or profile_url,
            "profile_image_url": profile_image_url,
            "about_full": smart_truncate(about_full, 1400),
            "about_short": smart_truncate(about_short, 320),
            "top_skills": profile_top_skills,
            "last_synced_at": checked_at,
            "source": "linkedin",
        },
        "linkedin_experience": experience,
        "linkedin_featured": featured,
        "linkedin_updates": updates,
    }

    validate_payload(payload)
    if not has_minimum_profile_content(payload):
        raise LinkedInSyncError("LinkedIn seed payload did not contain enough profile fields to trust.")
    return payload


def load_seed_payload(path: Path, profile_url: str, checked_at: str, *, verbose: bool = False) -> dict[str, Any]:
    if not path.exists():
        raise LinkedInSyncError(f"LinkedIn seed file does not exist: {path}")

    raw_text = path.read_text(encoding="utf-8")
    if path.suffix.lower() == ".json":
        raw_data = json.loads(raw_text)
    else:
        raw_data = yaml.safe_load(raw_text) or {}

    if not isinstance(raw_data, dict):
        raise LinkedInSyncError("LinkedIn seed file must contain a top-level object.")

    payload = normalize_curated_seed(raw_data, profile_url, checked_at)
    if verbose:
        print(
            "Loaded curated LinkedIn seed: "
            f"profile={payload['linkedin_profile']['full_name'] or '<empty>'} "
            f"experience={len(payload['linkedin_experience'])} "
            f"featured={len(payload['linkedin_featured'])} "
            f"updates={len(payload['linkedin_updates'])}"
        )
    return payload


def build_experience_items(
    soup: BeautifulSoup,
    person: dict[str, Any],
    profile_url: str,
    location_fallback: str,
    about_full: str,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for card in parse_section_cards(soup, ("experience",)):
        headings = [clean_text(tag.get_text(" ", strip=True)) for tag in card.find_all(re.compile("^h[1-6]$"), limit=3)]
        paragraphs = [clean_text(tag.get_text(" ", strip=True)) for tag in card.find_all(["p", "span", "time"], limit=12)]
        bullet_tags = [clean_text(tag.get_text(" ", strip=True)) for tag in card.find_all("li", limit=6)]
        role = headings[0] if headings else ""
        organization = headings[1] if len(headings) > 1 else ""
        date_range = ""
        location = ""
        descriptive_chunks: list[str] = []

        for paragraph in paragraphs:
            if not date_range and re.search(r"\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|Present|\d{4})\b", paragraph):
                date_range = smart_truncate(paragraph, 80)
                continue
            if not location and "," in paragraph and len(paragraph) <= 100:
                location = smart_truncate(paragraph, 100)
                continue
            if not organization and paragraph and len(paragraph) <= 90:
                organization = smart_truncate(paragraph, 90)
                continue
            if len(paragraph) > 20:
                descriptive_chunks.append(paragraph)

        description_full = remove_duplicate_punctuation(" ".join(bullet_tags or descriptive_chunks))
        bullets = unique_preserve(bullet_tags or sentence_bullets(description_full), 4, max_length=180)

        if not role and not organization:
            continue

        items.append(
            {
                "id": stable_id("experience", role, organization, date_range or location),
                "role": smart_truncate(role, 90),
                "organization": smart_truncate(organization, 90),
                "date_range": smart_truncate(date_range, 80),
                "location": smart_truncate(location or location_fallback, 100),
                "description_full": smart_truncate(description_full, 900),
                "description_short": smart_truncate(description_full, 240),
                "bullets": bullets,
                "canonical_url": extract_anchor_url(card, profile_url),
                "source": "linkedin",
            }
        )
        if len(items) >= 8:
            break

    if items:
        return items

    headline = clean_text(str(person.get("jobTitle") or ""))
    current_role, organization = split_role_and_org(headline)
    works_for = person.get("worksFor") or {}
    if isinstance(works_for, list):
        first_org = works_for[0] if works_for else {}
    else:
        first_org = works_for
    organization = organization or clean_text(str((first_org or {}).get("name") or first_org or ""))
    if not current_role and not organization:
        return []

    fallback_bullets = sentence_bullets(about_full)
    return [
        {
            "id": stable_id("experience", current_role, organization, "current-role"),
            "role": smart_truncate(current_role, 90),
            "organization": smart_truncate(organization, 90),
            "date_range": "Current role",
            "location": smart_truncate(location_fallback, 100),
            "description_full": smart_truncate(about_full, 900),
            "description_short": smart_truncate(about_full, 240),
            "bullets": unique_preserve(fallback_bullets, 4, max_length=180),
            "canonical_url": strip_tracking_url(profile_url),
            "source": "linkedin",
        }
    ]


def build_featured_items(soup: BeautifulSoup, profile_url: str) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for card in parse_section_cards(soup, ("featured",)):
        anchor = card.find("a", href=True)
        title = clean_text(anchor.get_text(" ", strip=True) if anchor else "")
        if not title:
            continue
        texts = [clean_text(tag.get_text(" ", strip=True)) for tag in card.find_all(["p", "span"], limit=6)]
        subtitle = texts[0] if texts else "Featured item"
        summary_source = next((text for text in texts[1:] if len(text) > 24), "")
        item_type = detect_item_type(title, subtitle, "link")
        items.append(
            {
                "id": stable_id("featured", title, subtitle),
                "type": item_type,
                "title": smart_truncate(title, 80),
                "subtitle": smart_truncate(subtitle, 80),
                "summary_full": smart_truncate(summary_source, 900),
                "summary_short": smart_truncate(summary_source or subtitle, 220),
                "url": extract_anchor_url(card, profile_url),
                "source": "linkedin",
            }
        )
        if len(items) >= 6:
            break
    return items


def build_update_items(soup: BeautifulSoup, profile_url: str) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for card in parse_section_cards(soup, ("activity", "posts", "updates")):
        anchor = card.find("a", href=True)
        title = clean_text(anchor.get_text(" ", strip=True) if anchor else "")
        if not title:
            continue
        time_node = card.find("time")
        posted_relative = normalize_relative_label(time_node.get_text(" ", strip=True) if time_node else "")
        texts = [clean_text(tag.get_text(" ", strip=True)) for tag in card.find_all(["p", "span"], limit=8)]
        summary_source = next((text for text in texts if len(text) > 28 and text.casefold() != title.casefold()), "")
        items.append(
            {
                "id": stable_id("update", title, posted_relative),
                "kind": detect_update_kind(title, summary_source),
                "title": smart_truncate(title, 80),
                "summary_full": smart_truncate(summary_source, 900),
                "summary_short": smart_truncate(summary_source or title, 220),
                "posted_relative": posted_relative,
                "canonical_url": extract_anchor_url(card, profile_url),
                "source": "linkedin",
            }
        )
        if len(items) >= 3:
            break
    return items


def dedupe_featured_and_updates(
    featured: list[dict[str, Any]],
    updates: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    seen = {
        (
            item.get("url") or item.get("canonical_url") or "",
            slugify(item.get("title") or ""),
        )
        for item in featured
    }
    filtered_updates: list[dict[str, Any]] = []
    for item in updates:
        key = (item.get("canonical_url") or "", slugify(item.get("title") or ""))
        if key in seen:
            continue
        filtered_updates.append(item)
    return featured, filtered_updates


def extract_profile_payload(html: str, profile_url: str, checked_at: str, *, verbose: bool = False) -> dict[str, Any]:
    soup = soup_parser(html)
    records = extract_json_ld_records(soup)
    person = find_person_record(records)

    og_title = first_meta(soup, ("property", "og:title"), ("name", "title"))
    description = first_meta(soup, ("name", "description"), ("property", "og:description"))
    profile_image = first_meta(soup, ("property", "og:image"))
    full_name = smart_truncate(clean_text(str(person.get("name") or "")) or clean_text(og_title.replace("| LinkedIn", "")), 120)

    raw_headline = clean_text(str(person.get("jobTitle") or ""))
    segments = meta_description_segments(description)
    if not raw_headline and segments:
        raw_headline = segments[0]
    headline = smart_truncate(raw_headline, 220)
    current_role, organization = split_role_and_org(headline)
    if not organization:
        works_for = person.get("worksFor") or {}
        if isinstance(works_for, list):
            works_for = works_for[0] if works_for else {}
        organization = smart_truncate(clean_text(str((works_for or {}).get("name") or works_for or "")), 120)

    about_full = clean_text(str(person.get("description") or ""))
    if not about_full and len(segments) >= 3:
        about_full = " - ".join(segments[2:])
    if not about_full:
        about_full = description

    location = parse_location(soup, person, description)
    top_skills = parse_top_skills(soup)
    experience = build_experience_items(soup, person, profile_url, location, about_full)
    featured = build_featured_items(soup, profile_url)
    updates = build_update_items(soup, profile_url)
    featured, updates = dedupe_featured_and_updates(featured, updates)

    payload = {
        "linkedin_profile": {
            "full_name": full_name,
            "headline": headline,
            "headline_short": smart_truncate(headline, 110),
            "location": smart_truncate(location, 120),
            "organization": smart_truncate(organization, 120),
            "current_role": smart_truncate(current_role, 120),
            "profile_url": strip_tracking_url(profile_url) or profile_url,
            "profile_image_url": strip_tracking_url(profile_image) or "",
            "about_full": smart_truncate(about_full, 1400),
            "about_short": smart_truncate(about_full, 320),
            "top_skills": unique_preserve(top_skills, 8, max_length=40),
            "last_synced_at": checked_at,
            "source": "linkedin",
        },
        "linkedin_experience": experience,
        "linkedin_featured": featured,
        "linkedin_updates": updates,
    }

    if verbose:
        print(
            "Parsed LinkedIn payload: "
            f"profile={bool(full_name)} experience={len(experience)} "
            f"featured={len(featured)} updates={len(updates)}"
        )

    return payload


def has_minimum_profile_content(payload: dict[str, Any]) -> bool:
    profile = payload.get("linkedin_profile") or {}
    if any(not clean_text(str(profile.get(field) or "")) for field in PROFILE_REQUIRED_FIELDS):
        return False
    return True


def validator() -> Draft202012Validator:
    return Draft202012Validator(SCHEMA)


def validate_payload(payload: dict[str, Any]) -> None:
    errors = sorted(validator().iter_errors(payload), key=lambda error: list(error.absolute_path))
    if errors:
        messages = []
        for error in errors[:10]:
            path = ".".join(str(part) for part in error.absolute_path) or "<root>"
            messages.append(f"{path}: {error.message}")
        raise LinkedInSyncError("Schema validation failed: " + "; ".join(messages))


def canonical_content(payload: dict[str, Any]) -> dict[str, Any]:
    canonical = copy.deepcopy(payload)
    profile = canonical.get("linkedin_profile") or {}
    profile.pop("last_synced_at", None)
    for key in ("linkedin_experience", "linkedin_featured", "linkedin_updates"):
        items = canonical.get(key) or []
        canonical[key] = sorted(items, key=lambda item: item.get("id") or "")
    return canonical


def content_hash(payload: dict[str, Any]) -> str:
    serialized = json.dumps(canonical_content(payload), ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def summarize_diff(previous: dict[str, Any] | None, current: dict[str, Any]) -> list[str]:
    current_canonical = canonical_content(current)
    previous_canonical = canonical_content(previous or {})
    changes: list[str] = []

    previous_profile = previous_canonical.get("linkedin_profile") or {}
    current_profile = current_canonical.get("linkedin_profile") or {}
    for field in ("headline_short", "location", "organization", "about_short", "top_skills"):
        if previous_profile.get(field) != current_profile.get(field):
            changes.append(f"linkedin_profile.{field}")

    for section_name in ("linkedin_experience", "linkedin_featured", "linkedin_updates"):
        if previous_canonical.get(section_name) != current_canonical.get(section_name):
            changes.append(section_name)

    deduped: list[str] = []
    for change in changes:
        if change not in deduped:
            deduped.append(change)
    return deduped


def payload_score(payload: dict[str, Any]) -> int:
    profile = payload.get("linkedin_profile") or {}
    total = 0
    total += len(clean_text(profile.get("headline") or ""))
    total += len(clean_text(profile.get("about_short") or ""))
    total += 20 * len(profile.get("top_skills") or [])
    total += 90 * len(payload.get("linkedin_experience") or [])
    total += 65 * len(payload.get("linkedin_featured") or [])
    total += 55 * len(payload.get("linkedin_updates") or [])
    return total


def is_suspiciously_empty(payload: dict[str, Any], previous: dict[str, Any] | None) -> bool:
    if not previous:
        return False
    previous_score = payload_score(previous)
    current_score = payload_score(payload)
    if previous_score >= 220 and current_score < int(previous_score * 0.35):
        return True

    dropped_sections = 0
    for section_name in ("linkedin_experience", "linkedin_featured", "linkedin_updates"):
        previous_count = len(previous.get(section_name) or [])
        current_count = len(payload.get(section_name) or [])
        if previous_count >= 2 and current_count == 0:
            dropped_sections += 1
    return dropped_sections >= 2


def load_existing_snapshot() -> dict[str, Any] | None:
    snapshot_path = DATA_DIR / "linkedin_snapshot.json"
    if not snapshot_path.exists():
        return None
    try:
        payload = json.loads(snapshot_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise LinkedInSyncError(f"Existing linkedin_snapshot.json is invalid JSON: {error}") from error

    if isinstance(payload, dict) and payload.get("linkedin_profile"):
        return payload
    raise LinkedInSyncError("Existing linkedin_snapshot.json does not match the expected LinkedIn snapshot shape.")


def current_sync_meta(snapshot: dict[str, Any] | None) -> dict[str, Any]:
    if not snapshot or not isinstance(snapshot, dict):
        return {}
    meta = snapshot.get("linkedin_sync_meta") or {}
    return meta if isinstance(meta, dict) else {}


def has_successful_snapshot(snapshot: dict[str, Any] | None) -> bool:
    return current_sync_meta(snapshot).get("sync_status") == "ok"


def build_sync_meta(
    payload: dict[str, Any],
    profile_url: str,
    checked_at: str,
    *,
    source: str = PUBLIC_SYNC_SOURCE,
    warning: str = "",
) -> dict[str, Any]:
    digest = content_hash(payload)
    source_tag = "seed" if source == CURATED_SEED_SOURCE else "public"
    asset_version = f"linkedin-{source_tag}-{checked_at.replace(':', '').replace('+00:00', 'z')[:15]}-{digest[:8]}"
    return {
        "sync_status": "ok",
        "source": source,
        "profile_url": strip_tracking_url(profile_url) or profile_url,
        "schema_version": SCHEMA_VERSION,
        "last_attempted_sync_at": checked_at,
        "last_successful_sync_at": checked_at,
        "last_meaningful_change_at": checked_at,
        "generated_asset_version": asset_version,
        "content_hash": digest,
        "generator": "scripts/sync_linkedin_content.py",
        "warning": warning,
    }


def build_bundle(payload: dict[str, Any], sync_meta: dict[str, Any]) -> dict[str, Any]:
    return {
        "linkedin_profile": {"linkedin_profile": payload["linkedin_profile"]},
        "linkedin_experience": {"linkedin_experience": payload["linkedin_experience"]},
        "linkedin_featured": {"linkedin_featured": payload["linkedin_featured"]},
        "linkedin_updates": {"linkedin_updates": payload["linkedin_updates"]},
        "linkedin_sync_meta": {"linkedin_sync_meta": sync_meta},
        "linkedin_snapshot": {
            **payload,
            "linkedin_sync_meta": sync_meta,
            "_machine_managed": True,
        },
    }


def dump_yaml_document(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=False, default_flow_style=False)


def generated_js_content(bundle: dict[str, Any]) -> str:
    snapshot = bundle["linkedin_snapshot"]
    payload = {
        "meta": snapshot["linkedin_sync_meta"],
        "profile": snapshot["linkedin_profile"],
        "experience": snapshot["linkedin_experience"],
        "featured": snapshot["linkedin_featured"],
        "updates": snapshot["linkedin_updates"],
    }
    return (
        "/* MACHINE-MANAGED FILE. DO NOT EDIT. */\n"
        "window.LINKEDIN_SYNC = Object.freeze("
        + json.dumps(payload, indent=2, ensure_ascii=True)
        + ");\n"
    )


def write_bundle(bundle: dict[str, Any]) -> list[Path]:
    writes: list[tuple[Path, str]] = [
        (DATA_DIR / "linkedin_profile.yml", MACHINE_HEADER + dump_yaml_document(bundle["linkedin_profile"])),
        (DATA_DIR / "linkedin_experience.yml", MACHINE_HEADER + dump_yaml_document(bundle["linkedin_experience"])),
        (DATA_DIR / "linkedin_featured.yml", MACHINE_HEADER + dump_yaml_document(bundle["linkedin_featured"])),
        (DATA_DIR / "linkedin_updates.yml", MACHINE_HEADER + dump_yaml_document(bundle["linkedin_updates"])),
        (DATA_DIR / "linkedin_sync_meta.yml", MACHINE_HEADER + dump_yaml_document(bundle["linkedin_sync_meta"])),
        (
            DATA_DIR / "linkedin_snapshot.json",
            json.dumps(bundle["linkedin_snapshot"], indent=2, ensure_ascii=True) + "\n",
        ),
        (ASSET_DIR / "linkedin.generated.js", generated_js_content(bundle)),
    ]

    written_paths: list[Path] = []
    for path, content in writes:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written_paths.append(path)
    return written_paths


def build_placeholder_bundle(profile_url: str) -> dict[str, Any]:
    sync_meta = {
        "sync_status": "unavailable",
        "source": PUBLIC_SYNC_SOURCE,
        "profile_url": profile_url,
        "schema_version": SCHEMA_VERSION,
        "last_attempted_sync_at": "",
        "last_successful_sync_at": "",
        "last_meaningful_change_at": "",
        "generated_asset_version": "linkedin-bootstrap",
        "content_hash": "",
        "generator": "scripts/sync_linkedin_content.py",
        "warning": "Live LinkedIn sync has not produced validated content yet.",
    }
    payload = {
        "linkedin_profile": {
            "full_name": "",
            "headline": "",
            "headline_short": "",
            "location": "",
            "organization": "",
            "current_role": "",
            "profile_url": profile_url,
            "profile_image_url": "",
            "about_full": "",
            "about_short": "",
            "top_skills": [],
            "last_synced_at": "",
            "source": "linkedin",
        },
        "linkedin_experience": [],
        "linkedin_featured": [],
        "linkedin_updates": [],
    }
    return build_bundle(payload, sync_meta)


def read_source_payload(path: Path) -> FetchResult:
    raw_text = path.read_text(encoding="utf-8")
    fetched_at = dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()

    if path.suffix.lower() == ".json":
        raw_data = json.loads(raw_text)
        html = raw_data.get("html") or ""
        profile_url = raw_data.get("url") or raw_data.get("final_url") or ""
        final_url = raw_data.get("final_url") or profile_url
        status_code = int(raw_data.get("status_code") or 200)
        fetched_at = raw_data.get("fetched_at") or fetched_at
        return FetchResult(
            url=profile_url,
            final_url=final_url,
            status_code=status_code,
            fetched_at=fetched_at,
            html=html,
        )

    return FetchResult(
        url="",
        final_url="",
        status_code=200,
        fetched_at=fetched_at,
        html=raw_text,
    )
